local cpconfig = {
  {"Vim",
    { "reload vimrc", ":source $MYVIMRC" },
    { 'check health', ":checkhealth" },
    { "jumps (Alt-j)", ":lua require('telescope.builtin').jumplist()" },
    { "commands", ":lua require('telescope.builtin').commands()" },
    { "command history", ":lua require('telescope.builtin').command_history()" },
    { "registers (A-e)", ":lua require('telescope.builtin').registers()" },
    { "colorshceme", ":lua require('telescope.builtin').colorscheme()", 1 },
    { "vim options", ":lua require('telescope.builtin').vim_options()" },
    { "keymaps", ":lua require('telescope.builtin').keymaps()" },
    { "buffers", ":Telescope buffers" },
    { "search history (C-h)", ":lua require('telescope.builtin').search_history()" },
    { "paste mode", ':set paste!' },
    { 'cursor line', ':set cursorline!' },
    { 'cursor column', ':set cursorcolumn!' },
    { "spell checker", ':set spell!' },
    { "relative number", ':set relativenumber!' },
    { "search highlighting (F12)", ':set hlsearch!' },
  },
  {"General",
    { "Command palette (<ldr>-tcp)", ":Telescope command_palette<CR>" },
    { "Default binds cheetsheet (<ldr>-ch)", ""},
    { "Key-bind search", ":Telescope mappings<CR>"},
    { "Loc-list ", ":Telescope loclist<CR>"},
    { "Buffers", ":Telescope buffers<CR>"},
    { "Registers", ":Telescope registers<CR>"},
    { "Jumplist", ":Telescope jumplist<CR>"},
  },
  {"LSP",
    { "LSP Reference (<ldr>-lr)", ":Telescope lsp_references <CR>"},
    { "LSP Document symbolds (<ldr>-ls)", ":Telescope lsp_document_symbols<CR>"},
  }
}

return cpconfig
