-- Current understanding: The top level init.lua, (outside lua folder) calls
-- loads the three main modules, [options, mappings, plugins]. These files
-- internally then use the custom settings to overwrite their own settings. The
-- custom folder mainly just contains lua tables with custom values and
-- functions. These are then passed on to the appropriate variable (see
-- chardrc) so that they are applied on load.
--
--
-- Plugins and Plugin Settings
-- --------------------------
-- Plugin information is localized to custom.plugins module and are loaded from
-- custom.chadrc.
